services: ##Quais containers/servicos tem o projeto
  app: ## nome do servi√ßo 
    build: . ## Construa a imagem rodando o dockerfile desta pasta
    ports:
    - "3000:3000" ## acessa no pc a porta 3000 e o compose encaminha isso para a porta 3000 do container
    volumes:
    - .:/home/node/app ## tudo que esta na pasta project2 aparece em /home/node/app dentro do container

  redis:
    image: redis:7-alpine
    container_name: meu_redis
    ports:
    - "6379:6379"
    volumes:
      - redisdata:/data
volumes:
  redisdata:
    